// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TwitterServiceClient is the client API for TwitterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TwitterServiceClient interface {
	SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type twitterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTwitterServiceClient(cc grpc.ClientConnInterface) TwitterServiceClient {
	return &twitterServiceClient{cc}
}

func (c *twitterServiceClient) SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/proto.TwitterService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwitterServiceServer is the server API for TwitterService service.
// All implementations must embed UnimplementedTwitterServiceServer
// for forward compatibility
type TwitterServiceServer interface {
	SayHello(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedTwitterServiceServer()
}

// UnimplementedTwitterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTwitterServiceServer struct {
}

func (UnimplementedTwitterServiceServer) SayHello(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedTwitterServiceServer) mustEmbedUnimplementedTwitterServiceServer() {}

// UnsafeTwitterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwitterServiceServer will
// result in compilation errors.
type UnsafeTwitterServiceServer interface {
	mustEmbedUnimplementedTwitterServiceServer()
}

func RegisterTwitterServiceServer(s grpc.ServiceRegistrar, srv TwitterServiceServer) {
	s.RegisterService(&TwitterService_ServiceDesc, srv)
}

func _TwitterService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TwitterService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterServiceServer).SayHello(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// TwitterService_ServiceDesc is the grpc.ServiceDesc for TwitterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TwitterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TwitterService",
	HandlerType: (*TwitterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _TwitterService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
